name: CICD

on:
  push:
    branches:
      - '*'

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: yarn
      - run: yarn lint

  build-prod:
    needs: lint
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  deploy-prod:
    needs: build-prod
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE_DIR: /home/up/website
      COMPOSE_FILE_NAME: website-docker-compose.yaml
      WEB_SERVER_SSH_PRIVATE_KEY: ${{secrets.PROD_WEB_SERVER_SSH_PRIVATE_KEY}}
      WEB_SERVER_SSH_HOST: ${{secrets.PROD_WEB_SERVER_SSH_HOST}}
      REGISTRY_USERNAME: ${{secrets.REGISTRY_USERNAME}}
      REGISTRY_TOKEN: ${{secrets.REGISTRY_TOKEN}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: bash ./scripts/setup_ssh.sh

      - name: Server Deployment
        run: bash ./scripts/deployment.sh